# Site wide configuration

title:            Yannick PEREIRA-REIS
locale:           en_US
url:              https://ypereirareis.github.io

# Jekyll configuration

permalink: /blog/:year/:month/:day/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

comments: true

highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  syntax_highlighter: rouge

# Site owner
owner:
  name: Yannick PEREIRA-REIS
  avatar: author/avatar.png
  bio: "Full stack web developer Symfony2, VueJs and AngularJs in Lyon (France), I also play with DevOps tools like Docker, Vagrant, Elasticsearch, Logstash, Kibana, Supervisor, ..."
  disqus-shortname: ypereirareisgithubio
  google:
    analytics: UA-60388348-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  twitter: yannickpr69
  github: ypereirareis
  linkedin: yannickpereirareis

include: [".htaccess"]
exclude: ["cache", "lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
